# Generated by Django 5.2.11 on 2026-08-20 07:21
# Modifiée pour gérer les enregistrements existants avec des UUID dupliqués.

import uuid
from django.db import migrations, models


def generate_unique_keys(apps, schema_editor):
    """Génère un UUID unique pour chaque Payment existant."""
    Payment = apps.get_model('sales', 'Payment')
    for payment in Payment.objects.all():
        payment.idempotency_key = uuid.uuid4()
        payment.save(update_fields=['idempotency_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoice_customer_phone'),
    ]

    operations = [
        # Étape 1 : ajouter le champ SANS contrainte unique (nullable temporairement)
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Étape 2 : générer des UUID uniques pour les enregistrements existants
        migrations.RunPython(generate_unique_keys, migrations.RunPython.noop),
        # Étape 3 : rendre le champ unique et non-nullable
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('invoice', 'method'), name='unique_payment_per_invoice_method'),
        ),
    ]
