# Generated by Django 5.0.6 on 2024-05-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAppro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Approvisionnement',
                'verbose_name_plural': 'Approvisionnements',
                'db_table': 'db_Approvisionnement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetailAppro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(default=0)),
                ('Appro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.approvisionnement')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.product')),
            ],
            options={
                'verbose_name': 'DetailAppro',
                'verbose_name_plural': 'DetailAppros',
                'db_table': 'db_DetailAppro',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='Product',
            field=models.ManyToManyField(related_name='Product_Appro_Items', through='stock.DetailAppro', to='article.product'),
        ),
        migrations.CreateModel(
            name='DetailSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(default=0)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.product')),
            ],
            options={
                'verbose_name': 'DetailSortie',
                'verbose_name_plural': 'DetailSorties',
                'db_table': 'db_DetailSortie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SortieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateSortie', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ManyToManyField(related_name='Product_Sortie_Items', through='stock.DetailSortie', to='article.product')),
            ],
            options={
                'verbose_name': 'SortieStock',
                'verbose_name_plural': 'SortieStocks',
                'db_table': 'db_SortieStock',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='detailsortie',
            name='Sortie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sortiestock'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(default=0)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'db_Stock',
                'managed': True,
            },
        ),
    ]
