# Generated by Django 5.1.2 on 2024-11-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailAppro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.product')),
            ],
            options={
                'verbose_name': 'DetailAppro',
                'verbose_name_plural': 'DetailAppros',
                'db_table': 't_DetailAppro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetailSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.product')),
            ],
            options={
                'verbose_name': 'DetailSortie',
                'verbose_name_plural': 'DetailSorties',
                'db_table': 't_DetailSortie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEntree', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ManyToManyField(related_name='Product_Appro_Items', through='stock.DetailAppro', to='article.product')),
            ],
            options={
                'verbose_name': 'Entrée',
                'verbose_name_plural': 'Entées',
                'db_table': 't_Entree',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='detailappro',
            name='entree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.entree'),
        ),
        migrations.CreateModel(
            name='SortieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSortie', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(verbose_name='Motif de sortie')),
                ('product', models.ManyToManyField(related_name='Product_Sortie_Items', through='stock.DetailSortie', to='article.product')),
            ],
            options={
                'verbose_name': 'SortieStock',
                'verbose_name_plural': 'SortieStocks',
                'db_table': 't_SortieStock',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='detailsortie',
            name='sortie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sortiestock'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, verbose_name='Qté en stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 't_Stock',
                'managed': True,
            },
        ),
    ]
