# Generated by Django 5.2.11 on 2026-08-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mon supermarché', max_length=150)),
                ('currency', models.CharField(default='FC', max_length=8)),
                ('invoice_prefix', models.CharField(default='FAC', max_length=20)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('expiry_alert_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'store settings',
            },
        ),
    ]
