# Generated by Django 5.2.11 on 2026-08-18 10:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storesettings_discounts_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
