# Generated by Django 5.2.17 on 2026-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_storesettings_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='ccm_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='contact',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='national_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
