# Generated by Django 5.0.6 on 2024-05-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, unique=True, verbose_name='Catégorie')),
                ('Status', models.CharField(choices=[('Actif', 'Actif '), ('Désactivé', 'Désactivé')], max_length=250, unique=True, verbose_name='Statut')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'db_table': 'db_Categorie',
                'managed': True,
            },
        ),
    ]
