# Generated by Django 5.0.6 on 2024-05-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='Status',
            field=models.CharField(choices=[('Actif', 'Actif '), ('Désactivé', 'Désactivé')], max_length=250, verbose_name='Statut'),
        ),
    ]
