# Generated by Django 5.1.2 on 2024-11-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Catégorie'),
        ),
    ]
