# Generated by Django 5.0.6 on 2024-05-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(max_length=250)),
                ('Status', models.BooleanField(default=False)),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
            ],
            options={
                'verbose_name': 'UniteVente',
                'verbose_name_plural': 'UniteVentes',
                'db_table': 'db_UniteVente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=8)),
                ('Name', models.TextField(max_length=400)),
                ('Marque', models.CharField(max_length=150)),
                ('QtyValue', models.PositiveIntegerField()),
                ('ProductType', models.CharField(choices=[('Simple', 'Simple '), ('Varié', 'Varié')], max_length=50, verbose_name='Type produit')),
                ('BarreCode', models.CharField(max_length=50, verbose_name='Barre Code')),
                ('StockAlert', models.IntegerField()),
                ('Expiry', models.BooleanField(default=False)),
                ('PrixVente', models.FloatField()),
                ('DateFab', models.DateTimeField()),
                ('DateExp', models.DateTimeField()),
                ('Status', models.BooleanField(default=False)),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorie')),
                ('Unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.unitevente')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'db_Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductCodeBarre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeBarre', models.CharField(max_length=30)),
                ('Status', models.BooleanField(default=False)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.product')),
            ],
            options={
                'verbose_name': 'ProductCodeBarre',
                'verbose_name_plural': 'ProductCodeBarres',
                'db_table': 'db_ProductCodeBarre',
                'managed': True,
            },
        ),
    ]
