# Generated by Django 5.1.2 on 2024-11-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=250)),
                ('unitTag', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'UniteVente',
                'verbose_name_plural': 'UniteVentes',
                'db_table': 't_UniteVente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeRef', models.CharField(max_length=8)),
                ('libelle', models.TextField(max_length=400)),
                ('qteEnVente', models.PositiveIntegerField(default=1, verbose_name='Qté en vente')),
                ('productType', models.CharField(choices=[('Simple', 'Simple '), ('Varié', 'Varié')], max_length=50, verbose_name='Type de produit')),
                ('barreCode', models.CharField(max_length=50, verbose_name='Barre Code')),
                ('stockAlert', models.IntegerField(default=5, verbose_name='Stock alerte')),
                ('canExpiried', models.BooleanField(default=False)),
                ('pu', models.FloatField(verbose_name='Prix de vente')),
                ('manuf_on', models.DateTimeField()),
                ('expiried_on', models.DateTimeField()),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorie')),
                ('unity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.unitevente')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 't_Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductCodeBarre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeBarre', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.product')),
            ],
            options={
                'verbose_name': 'ProductCodeBarre',
                'verbose_name_plural': 'ProductCodeBarres',
                'db_table': 't_ProductCodeBarre',
                'managed': True,
            },
        ),
    ]
