# Generated by Django 5.0.6 on 2024-05-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(choices=[('Simple', 'Simple '), ('Varié', 'Varié')], max_length=250, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='productcodebarre',
            name='Status',
            field=models.CharField(choices=[('Activée', 'Activée '), ('Désactivée', 'Désactivée')], max_length=250, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='unitevente',
            name='Status',
            field=models.CharField(choices=[('Activée', 'Activée '), ('Désactivée', 'Désactivée')], max_length=250, verbose_name='Statut'),
        ),
    ]
