# Generated by Django 5.0.6 on 2024-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_product_status_alter_productcodebarre_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitevente',
            name='UnitTag',
            field=models.CharField(default='Kg', max_length=5),
            preserve_default=False,
        ),
    ]
