# Generated by Django 5.1.2 on 2024-11-06 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_product_pu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de creation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='codeRef',
            field=models.CharField(max_length=8, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='libelle',
            field=models.CharField(max_length=255, unique=True, verbose_name='Libellé'),
        ),
    ]
