# Generated by Django 5.1.2 on 2024-11-07 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_product_created_at_alter_product_coderef_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeRef', models.CharField(max_length=8, unique=True, verbose_name='Code')),
                ('varianteValue', models.CharField(max_length=200, verbose_name='Variante')),
                ('qteEnVente', models.PositiveIntegerField(default=1, verbose_name='Qté en vente')),
                ('canExpiried', models.BooleanField(default=False)),
                ('pu', models.PositiveIntegerField(default=0, verbose_name='Prix de vente')),
                ('manuf_on', models.DateTimeField()),
                ('expiried_on', models.DateTimeField()),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de creation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.product')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'db_table': 't_Variante',
                'managed': True,
            },
        ),
    ]
