# Generated by Django 5.1.2 on 2024-11-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_variantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barreCode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='canExpiried',
        ),
        migrations.RemoveField(
            model_name='product',
            name='codeRef',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiried_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manuf_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qteEnVente',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Déscription'),
        ),
        migrations.AddField(
            model_name='variantes',
            name='barreCode',
            field=models.CharField(default='0000000000000', max_length=50, verbose_name='Barre Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcodebarre',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.variantes'),
        ),
    ]
