# Generated by Django 5.1.2 on 2024-11-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_product_barrecode_remove_product_canexpiried_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantes',
            name='manuf_on',
        ),
        migrations.AlterField(
            model_name='variantes',
            name='expiried_on',
            field=models.DateField(),
        ),
    ]
