# Generated by Django 5.2.11 on 2026-08-17 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('promotion_type', models.CharField(choices=[('PERCENT', 'Pourcentage'), ('FIXED', 'Montant fixe')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='products.category')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='products.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['active', 'starts_at', 'ends_at', 'priority'], name='promotions__active_fabf28_idx')],
            },
        ),
    ]
