# Generated by Django 5.1.2 on 2024-11-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.PositiveBigIntegerField()),
                ('estConfirme', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cash',
                'verbose_name_plural': 'Cash',
                'db_table': 't_Cash',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntreeCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.PositiveBigIntegerField()),
                ('motif', models.TextField()),
                ('estConfirme', models.BooleanField(default=False)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.cash')),
            ],
            options={
                'verbose_name': 'Entree_stock',
                'verbose_name_plural': 'Entree_stocks',
                'db_table': 't_Entree_Stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SortieCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.PositiveBigIntegerField()),
                ('motif', models.TextField()),
                ('estConfirme', models.BooleanField(default=False)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.cash')),
            ],
            options={
                'verbose_name': 'Sortie_stock',
                'verbose_name_plural': 'Sortie_stocks',
                'db_table': 't_Sortie_Stock',
                'managed': True,
            },
        ),
    ]
