from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from apps.products.models import ProductVariant
from apps.suppliers.models import Supplier


class ReplenishmentNeed(models.Model):
    """Need generated by stock services, awaiting conversion into a supplier order."""
    class Status(models.TextChoices):
        OPEN = "OPEN", "À commander"
        ORDERED = "ORDERED", "Commandé"
        RESOLVED = "RESOLVED", "Résolu"

    variant = models.ForeignKey(ProductVariant, on_delete=models.PROTECT, related_name="replenishment_needs")
    threshold_snapshot = models.PositiveIntegerField()
    available_snapshot = models.PositiveIntegerField()
    suggested_quantity = models.PositiveIntegerField()
    status = models.CharField(max_length=12, choices=Status.choices, default=Status.OPEN, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [models.UniqueConstraint(fields=["variant"], condition=models.Q(status="OPEN"), name="one_open_replenishment_need_per_variant")]
        ordering = ["-created_at"]

    def __str__(self):
        return f"Réapprovisionnement : {self.variant}"


class PurchaseOrder(models.Model):
    class Status(models.TextChoices): DRAFT="DRAFT","Brouillon"; ORDERED="ORDERED","Commandée"; PARTIAL="PARTIAL","Partiellement reçue"; RECEIVED="RECEIVED","Reçue"; CANCELLED="CANCELLED","Annulée"
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, related_name="purchase_orders")
    reference = models.CharField(max_length=80, unique=True)
    status = models.CharField(max_length=12, choices=Status.choices, default=Status.DRAFT)
    paid_in_cash = models.BooleanField(default=False)
    cash_session = models.ForeignKey("pos.CashSession", null=True, blank=True, on_delete=models.PROTECT, related_name="purchase_orders")
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self): return self.reference


class PurchaseOrderLine(models.Model):
    order = models.ForeignKey(PurchaseOrder, on_delete=models.PROTECT, related_name="lines")
    variant = models.ForeignKey(ProductVariant, on_delete=models.PROTECT)
    ordered_quantity = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    received_quantity = models.PositiveIntegerField(default=0)
    unit_cost = models.DecimalField(max_digits=14, decimal_places=2, validators=[MinValueValidator(0)])
    class Meta: constraints=[models.UniqueConstraint(fields=["order","variant"], name="one_variant_per_purchase_order")]
