# Generated by Django 5.2.11 on 2026-08-17 12:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('expires_at', models.DateField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateField(default=django.utils.timezone.localdate)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Réception'), ('SALE', 'Vente'), ('SALE_CANCELLED', 'Annulation vente'), ('RETURN', 'Retour'), ('ADJUSTMENT', 'Ajustement'), ('LOSS', 'Perte'), ('EXPIRY', 'Expiration')], max_length=24)),
                ('quantity_delta', models.IntegerField()),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklot')),
            ],
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['variant', 'expires_at'], name='inventory_s_variant_822a5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('variant', 'code'), name='unique_lot_per_variant'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_ed5291_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='stock_movement_delta_nonzero'),
        ),
    ]
