# Generated by Django 5.2.17 on 2026-08-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='inventory_reports/'),
        ),
    ]
