# Generated by Django 5.2.11 on 2026-08-17 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('CLOSED', 'Fermée')], default='OPEN', max_length=10)),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='pos.cashregister')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('register',), name='one_open_session_per_register')],
            },
        ),
    ]
