# Generated by Django 5.2.11 on 2026-08-17 13:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=3)),
                ('category', models.CharField(choices=[('OPENING_FLOAT', 'Fonds initial'), ('OWNER_DEPOSIT', 'Apport du responsable'), ('PURCHASE', 'Achat payé en espèces'), ('EXPENSE', 'Dépense'), ('WITHDRAWAL', 'Retrait'), ('EXCHANGE_IN', 'Change — espèces reçues'), ('EXCHANGE_OUT', 'Change — espèces remises'), ('ADJUSTMENT', 'Ajustement autorisé')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('foreign_currency', models.CharField(blank=True, max_length=8)),
                ('foreign_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('cashier',), name='one_open_session_per_cashier'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='pos.cashsession'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_cash_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['session', 'direction', 'created_at'], name='pos_cashtra_session_c8334c_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_transaction_positive_amount'),
        ),
    ]
