# Generated by Django 5.2.11 on 2026-08-18 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_cashtransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
